### ISSUE TITLE
No valid install plan

### ISSUE THREAD

**Issue by davean** [quchen/acme-everything#3]
I'm afraid, as exciting as your package appears, I was unable to install it due to dependency conflicts.

**Comment by quchen** [comment]
Yes, there are some bugs in the dependencies that do not allow it to be built. I'll email the respective maintainers to fix these issues as soon as possible.

**Comment by quchen** [comment]
This will likely never compile. Closing as **won't fix**.

I do have a useful `stackage-everything` generator though, which can come in handy to preload all packages for long airplane trips. https://github.com/quchen/stackage-everything
