### ISSUE TITLE
This package shows up in the Hackage reverse dependencies database

### ISSUE THREAD

**Issue by treeowl** [quchen/acme-everything#4]
While I appreciate the humor of this package, it seems a bit rude to have a package that shows up in every single reverse dependency listing. I think the author of this package should arrange for its exclusion from that database.

**Comment by quchen** [comment]
This is more of a filter rule in the reverse dependency project, and not an issue with this package, no? Maybe the ACME namespace should be skipped altogether in the reverse dependency database.

**Comment by ocramz** [comment]
@quchen I agree with @treeowl , it was a fun prank for a while but it's completely pointless and frankly quite annoying, neither of which we ask for when using Hackage. 
Shifting the responsibility of filtering it out to the maintainer of http://packdeps.haskellers.com/reverse is hostile. Moreover, the ACME namespace contains legitimate packages, which would be unduly removed. If deleting `acme-everything` is not an option, please consider editing its dependencies out with an explanation.

**Comment by quchen** [comment]
I agree that some might consider this package annoying. But it also serves a purpose beyond being funny (which is not something I’ll debate): it’s probably a weakness of Hackage if a single package can annoy a whole ecosystem. Cabal mirrors the entire package description DB as a tarball locally, so a hostile entity could simply flood the entirety of Cabal’s/Stack’s users with nonsensical giant `.cabal` files. I’d rather have `acme-everything` remind us of this than being DDOS’d by some script kiddie in the future if things aren’t patched.
